package Boundary.FormMonitoraOrdine;

import Boundary.Navigator;
import Controller.MonitoraOrdineController;
import Database.Session;
import Entity.Cliente;
import Entity.Ordine;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;


public class FormMonitoraOrdine {
    public JPanel contentPane;
    private JLabel titolo;
    private JTable tableOrdini;
    private JButton btnMonitora;
    private JLabel lblMessaggio;
    private JLabel lblStato;
    private JButton btn_indietro;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(5, 3, new Insets(0, 0, 0, 0), -1, -1));
        titolo = new JLabel();
        titolo.setText("Monitora lo stato dei tuoi ordini : ");
        contentPane.add(titolo, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setEnabled(true);
        contentPane.add(scrollPane1, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tableOrdini = new JTable();
        scrollPane1.setViewportView(tableOrdini);
        btnMonitora = new JButton();
        btnMonitora.setText("Recupera stato");
        contentPane.add(btnMonitora, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblMessaggio = new JLabel();
        lblMessaggio.setText("Label");
        contentPane.add(lblMessaggio, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblStato = new JLabel();
        lblStato.setText("Label");
        contentPane.add(lblStato, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btn_indietro = new JButton();
        btn_indietro.setText("<-");
        contentPane.add(btn_indietro, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    private final MonitoraOrdineController controller;
    private final Navigator navigator;

    public FormMonitoraOrdine(Navigator navigator) //questo costruttore viene chiamato quando apro la schermata
    {
        this.navigator = navigator;
        this.controller = new MonitoraOrdineController();

        InizializzaComponenti();

        btnMonitora.addActionListener(e -> monitoraOrdineSelezionato());
        btn_indietro.addActionListener(e -> tornaIndietro());


    }

    //imposto tutti gli elementi del mio form
    private void InizializzaComponenti() {
        lblMessaggio.setText("Caricamento degli ordini in corso..");
        lblStato.setText("Stato dell'ordine : -");

        tableOrdini.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); //PERMETTE DI SELEZIONARE SOLO UNA RIGA ALLA VOLTA
        svuotaTabella();
    }


    public void caricaOrdiniCliente() {
        Cliente cliente = (Cliente) Session.getInstance().getUtenteLoggato();

        if (cliente == null) {
            lblMessaggio.setText("Nessun utente autenticato!");
            lblStato.setText("Stato dell'ordine : -");
            svuotaTabella();
            return;
        }

        Long idCliente = cliente.getId();

        List<Ordine> ordini = controller.richiediListaOrdini(idCliente);

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID ordine");
        model.addColumn("Stato");

        if (ordini == null) {
            lblMessaggio.setText("Non hai ancora effettuato ordini");
            lblStato.setText("Stato dell'ordine : -");
            btnMonitora.setEnabled(false);
        } else {
            for (Ordine ordine : ordini) {
                model.addRow(new Object[]
                        {
                                ordine.getId(),
                                ordine.getStatoOrdine()
                        }
                );
            }

            lblMessaggio.setText("Ordini trovati : " + ordini.size());
            lblStato.setText("Seleziona un ordine e clicca sul pulsante Recupera Stato");
            btnMonitora.setEnabled(true);
        }

        tableOrdini.setModel(model);
    }


    private void monitoraOrdineSelezionato() {
        Cliente cliente = (Cliente) Session.getInstance().getUtenteLoggato();
        if (cliente == null) {
            JOptionPane.showMessageDialog(
                    contentPane,
                    "Nessun cliente autenticato.",
                    "Errore",
                    JOptionPane.ERROR_MESSAGE);


            navigator.showLogin();
            return;
        }

        int rigaSelezionata = tableOrdini.getSelectedRow();

        if (rigaSelezionata == -1) {
            JOptionPane.showMessageDialog(
                    contentPane,
                    "Seleziona prima un ordine dalla tabella.",
                    "Ordine non selezionato",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Object valoreId = tableOrdini.getValueAt(rigaSelezionata, 0);
        Long idOrdine = Long.valueOf(valoreId.toString());

        Long idCliente = cliente.getId();

        String stato = controller.richiediStatoOrdine(idOrdine, idCliente);

        lblStato.setText("Stato dell'ordine " + idOrdine + " : " + stato);
    }

    public void svuotaTabella() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID Ordine");
        model.addColumn("Stato");

        tableOrdini.setModel(model);
    }

    private void tornaIndietro() {
        navigator.showHome(); //da valutare
    }


}
