package Boundary;

import Controller.ListaRistorantiController;
import Entity.Ristorante;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.util.List;

public class FormListaRistoranti {
    JPanel contentPane;
    private JList ristorantiList;
    private JButton btnMonitoraOrdine;
    private Navigator navigator;

    public void caricaRistoranti() {
        List<Ristorante> ristoranti = ListaRistorantiController.getRistoranti();
        DefaultListModel<String> model = new DefaultListModel<>();
        if (ristoranti != null) {
            for (Ristorante r : ristoranti) {
                model.addElement(r.getNome());
            }
        }
        ristorantiList.setModel(model);
    }

    public FormListaRistoranti(Navigator navigator) {
        this.navigator = navigator;
        caricaRistoranti();

        ristorantiList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    String ristoranteSelezionato = (String) ristorantiList.getSelectedValue();
                    if (ristoranteSelezionato != null) {
                        navigator.setNomeRistorante(ristoranteSelezionato);
                        navigator.showOrdinazione();
                    }
                }
            }
        });
        btnMonitoraOrdine.addActionListener(e -> navigator.showMonitoraOrdine());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setInheritsPopupMenu(true);
        contentPane.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        ristorantiList = new JList();
        ristorantiList.setInheritsPopupMenu(false);
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        defaultListModel1.addElement("Ristorante 1");
        defaultListModel1.addElement("Ristorante 2");
        defaultListModel1.addElement("Ristorante 3");
        defaultListModel1.addElement("Ristorante 4");
        ristorantiList.setModel(defaultListModel1);
        ristorantiList.setValueIsAdjusting(false);
        ristorantiList.putClientProperty("List.isFileList", Boolean.FALSE);
        scrollPane1.setViewportView(ristorantiList);
        btnMonitoraOrdine = new JButton();
        btnMonitoraOrdine.setText("Monitora Ordine");
        contentPane.add(btnMonitoraOrdine, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
