package Boundary;

import Controller.OrdinazioneControllerStub;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class FormGestioneMenu {
    private JPanel contentPane;
    private JPanel Header;
    private JPanel Body;
    private JPanel Footer;
    private JList listPiatti;
    private JButton indietroButton;
    private JButton salvaButton;
    private JLabel NomeMenu;
    private JLabel lblNomeRistorante;


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /** Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        Header = new JPanel();
        Header.setLayout(new GridLayoutManager(1, 1, new Insets(2, 5, 2, 5), -1, -1));
        contentPane.add(Header, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        lblNomeRistorante = new JLabel();
        lblNomeRistorante.setText("NomeRistorante");
        Header.add(lblNomeRistorante, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Body = new JPanel();
        Body.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(Body, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        listPiatti = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        defaultListModel1.addElement("Piatto1");
        defaultListModel1.addElement("");
        defaultListModel1.addElement("Piatto2");
        defaultListModel1.addElement("");
        defaultListModel1.addElement("Piatto3");
        defaultListModel1.addElement("Piatto4");
        listPiatti.setModel(defaultListModel1);
        Body.add(listPiatti, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(450, 300), null, 0, false));
        NomeMenu = new JLabel();
        NomeMenu.setText("NomeMenu");
        Body.add(NomeMenu, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Footer = new JPanel();
        Footer.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(Footer, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        indietroButton = new JButton();
        indietroButton.setText("Indietro");
        Footer.add(indietroButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        salvaButton = new JButton();
        salvaButton.setText("Salva");
        Footer.add(salvaButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }


    //DA QUI IN POI è CODICE MIO
    public FormGestioneMenu() {
        salvaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SalvaModifiche();
            }
        });
    }

    private void SalvaModifiche() {
        String ristorante = lblNomeRistorante.getText();
        ArrayList<String> piatti = new ArrayList<String>();
        ArrayList<Integer> quantita = new ArrayList<Integer>();

        /*for (int i = 0; i < Body.getComponentCount(); i++) {
            Component c = Body.getComponent(i);
            if (c instanceof JPanel) {
                JPanel rigamenu = (JPanel) c;
                if (rigamenu.getComponentCount() > 0 && rigamenu.getComponent(0) instanceof JTextField) {
                    JTextField piatto = (JTextField) rigamenu.getComponent(0);
                    piatti.add(piatto.getText());
                    JSpinner quantita_ = (JSpinner) rigamenu.getComponent(1);

                    if ((int) quantita_.getValue() < 0) {
                        JOptionPane.showMessageDialog(null, "Inserire una quantità valida");
                    } else {
                        quantita.add((Integer) quantita_.getValue());
                    }
                }
            }
        }
        boolean esitoInserimento = OrdinazioneControllerStub.salvaOrdinazione(piatti, quantita);
        if (esitoInserimento) {
            lblesito.setText("Ordinazione salvata con successo");
            lblesito.setForeground(Color.GREEN);
        } else {
            lblesito.setText("Errore: Ordinazione non salvata");
            lblesito.setForeground(Color.RED);
        }*/
    }

    private void VaiAHome() {
        //qui va messo il codice per far ritornare l'uente alla schermata in cui deve scegliere tra i ristoranti
    }

    public static void main(String[] args) {
        JFrame frameGestioneMenu = new JFrame();
        FormGestioneMenu formGestioneMenu = new FormGestioneMenu();
        frameGestioneMenu.setTitle("Menu");
        frameGestioneMenu.setContentPane(formGestioneMenu.contentPane);
        frameGestioneMenu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frameGestioneMenu.setResizable(false);
        frameGestioneMenu.pack();
        frameGestioneMenu.setLocationRelativeTo(null);
        frameGestioneMenu.setVisible(true);
    }
}
