package Boundary;

import Controller.OrdinazioneControllerStub;
import Controller.RegisterController;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Objects;

public class FormOrdinazione {
    JPanel contentPane;
    private JButton indietroButton;
    private JButton confermaButton;
    private JTextField Piatto1;
    private JPanel Header;
    private JPanel Body;
    private JPanel Footer;
    private JSpinner spinner1;
    private JScrollBar scrollBar1;
    private JSpinner spinner2;
    private JSpinner spinner3;
    private JTextField Piatto2;
    private JTextField Piatto3;
    private JLabel NomeRistorante;
    private JLabel lblesito;
    private JTextField IndirizzotextField;
    private JLabel lblPrezzo;
    private JComboBox tipoStradaComboBox;
    private JTextField nCivicoTextField;
    private JTextField viaTextField;
    private JTextField cittaTextField;
    private JTextField capTextField;
    private JLabel indirizzoCosegnalbl;

    private final Navigator navigator;


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.setPreferredSize(new Dimension(800, 300));
        Header = new JPanel();
        Header.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, 2));
        contentPane.add(Header, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        NomeRistorante = new JLabel();
        NomeRistorante.setText("NomeRistorante");
        Header.add(NomeRistorante, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(99, 27), null, 0, false));
        Body = new JPanel();
        Body.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(Body, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        Body.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, true));
        Piatto1 = new JTextField();
        Piatto1.setEditable(false);
        Piatto1.setText("Piatto 1");
        panel1.add(Piatto1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(262, 34), null, 0, false));
        spinner1 = new JSpinner();
        panel1.add(spinner1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblPrezzo = new JLabel();
        lblPrezzo.setText("10.50");
        panel1.add(lblPrezzo, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        Body.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, true));
        Piatto2 = new JTextField();
        Piatto2.setEditable(false);
        Piatto2.setText("Piatto 2");
        panel2.add(Piatto2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(262, 34), null, 0, false));
        spinner2 = new JSpinner();
        panel2.add(spinner2, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Label");
        panel2.add(label1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        Body.add(panel3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, true));
        Piatto3 = new JTextField();
        Piatto3.setEditable(false);
        Piatto3.setText("Piatto 3");
        panel3.add(Piatto3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(262, 34), null, 0, false));
        spinner3 = new JSpinner();
        panel3.add(spinner3, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Label");
        panel3.add(label2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblesito = new JLabel();
        lblesito.setText("EsitoInserimento");
        Body.add(lblesito, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 6, new Insets(0, 0, 0, 0), -1, -1));
        Body.add(panel4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        indirizzoCosegnalbl = new JLabel();
        indirizzoCosegnalbl.setText("Indirizzo di Cosegna");
        panel4.add(indirizzoCosegnalbl, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tipoStradaComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Via");
        defaultComboBoxModel1.addElement("Viale");
        defaultComboBoxModel1.addElement("Piazza");
        defaultComboBoxModel1.addElement("Corso");
        defaultComboBoxModel1.addElement("Vicolo");
        defaultComboBoxModel1.addElement("Piazzale");
        defaultComboBoxModel1.addElement("Largo");
        defaultComboBoxModel1.addElement("Piazzetta");
        defaultComboBoxModel1.addElement("Vico");
        defaultComboBoxModel1.addElement("Vicoletto");
        defaultComboBoxModel1.addElement("Stradone");
        defaultComboBoxModel1.addElement("Salita");
        defaultComboBoxModel1.addElement("Contrada");
        defaultComboBoxModel1.addElement("Strada");
        defaultComboBoxModel1.addElement("Strada Comunale");
        defaultComboBoxModel1.addElement("Strada Provinciale");
        defaultComboBoxModel1.addElement("Traversa");
        defaultComboBoxModel1.addElement("Località");
        defaultComboBoxModel1.addElement("Borgo");
        defaultComboBoxModel1.addElement("Vialetto");
        defaultComboBoxModel1.addElement("Calle");
        defaultComboBoxModel1.addElement("Fondamenta");
        defaultComboBoxModel1.addElement("Sestiere");
        tipoStradaComboBox.setModel(defaultComboBoxModel1);
        panel4.add(tipoStradaComboBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, -1), null, 2, false));
        nCivicoTextField = new JTextField();
        nCivicoTextField.setColumns(50);
        panel4.add(nCivicoTextField, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(25, -1), null, 0, false));
        viaTextField = new JTextField();
        viaTextField.setColumns(20);
        viaTextField.setText("");
        viaTextField.setToolTipText("");
        panel4.add(viaTextField, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 2, false));
        cittaTextField = new JTextField();
        panel4.add(cittaTextField, new GridConstraints(0, 5, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, -1), null, 0, false));
        capTextField = new JTextField();
        panel4.add(capTextField, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, -1), null, 0, false));
        Footer = new JPanel();
        Footer.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(Footer, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        indietroButton = new JButton();
        indietroButton.setText("Indietro");
        Footer.add(indietroButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        confermaButton = new JButton();
        confermaButton.setText("Conferma");
        Footer.add(confermaButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scrollBar1 = new JScrollBar();
        contentPane.add(scrollBar1, new GridConstraints(1, 1, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }


    // DA QUI IN POI è CODICE MIO
    //

    public FormOrdinazione(Navigator navigator) {
        this.navigator = navigator;
        $$$setupUI$$$();
        confermaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //stampaDati(); PROVA LISTENER
                SalvaOrdinazione();
            }
        });
        indietroButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                VaiAListaRistoranti();
            }
        });
    }


    public void setNomeRistorante_e_POPUP() {
        NomeRistorante.setText(navigator.getNomeRistorante());
        setupPiattiListeners();
    }

    private void setupPiattiListeners() {
        for (int i = 0; i < Body.getComponentCount(); i++) {
            Component c = Body.getComponent(i);
            if (c instanceof JPanel) {
                JPanel rigamenu = (JPanel) c;
                if (rigamenu.getComponentCount() > 0 && rigamenu.getComponent(0) instanceof JTextField) {
                    JTextField piattoField = (JTextField) rigamenu.getComponent(0);
                    //piattoField.setToolTipText(p.descrizione);
                    addPiattoDescriptionPopup(piattoField);
                }
            }
        }
    }

    private void addPiattoDescriptionPopup(JTextField piattoField) {
        piattoField.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                String nomePiatto = piattoField.getText();
                String descrizione = "Descrizione di: " + nomePiatto;
                JOptionPane.showMessageDialog(contentPane, descrizione, nomePiatto, JOptionPane.INFORMATION_MESSAGE);
            }
        });
    }


    private void SalvaOrdinazione() {
        String ristorante = NomeRistorante.getText();

        String tipo = Objects.requireNonNull(tipoStradaComboBox.getSelectedItem()).toString();
        String via = tipo + " " + viaTextField.getText();
        String civico = nCivicoTextField.getText();
        String cap = capTextField.getText();
        String citta = cittaTextField.getText();

        String indirizzo = via + " " + civico + " " + cap + " " + citta;


        ArrayList<String> piatti = new ArrayList<String>();
        ArrayList<Integer> quantita = new ArrayList<Integer>();
        ArrayList<Float> prezzi = new ArrayList<Float>();

        boolean flag = false;

        for (int i = 0; i < Body.getComponentCount(); i++) {
            Component c = Body.getComponent(i);
            if (c instanceof JPanel rigamenu) {
                if (rigamenu.getComponentCount() > 0 && rigamenu.getComponent(0) instanceof JTextField piatto) {
                    JSpinner quantita_ = (JSpinner) rigamenu.getComponent(1);
                    JLabel prezzo = (JLabel) rigamenu.getComponent(2);

                    if ((int) quantita_.getValue() < 0) {
                        JOptionPane.showMessageDialog(null, "Inserire una quantità valida");
                        flag = true;
                    } else if (indirizzo.isBlank()) {
                        JOptionPane.showMessageDialog(null, "Inserire un indirizzo di consegna completo");
                        flag = true;
                    } else if ((int) quantita_.getValue() > 0) {
                        quantita.add((Integer) quantita_.getValue());

                        prezzi.add(Float.parseFloat(prezzo.getText()));
                        piatti.add(piatto.getText());
                    }
                }
            }
        }

        if (flag) {
            lblesito.setText("Errore: Ordinazione non salvata");
            lblesito.setForeground(Color.RED);
            return;
        }

        SalvaOrdinazioneAsync(piatti, quantita, via, civico, cap, citta);
    }

    private void SalvaOrdinazioneAsync(ArrayList<String> piatti, ArrayList<Integer> quantita, String via, String civico, String cap, String citta) {
        confermaButton.setEnabled(false);
        lblesito.setText("Salvataggio in corso...");
        lblesito.setForeground(Color.BLACK);

        SwingWorker<Boolean, Void> worker = new SwingWorker<Boolean, Void>() {
            @Override
            protected Boolean doInBackground() {
                return OrdinazioneControllerStub.salvaOrdinazione(piatti, quantita, via, civico, cap, citta);
            }

            @Override
            protected void done() {
                confermaButton.setEnabled(true);
                try {
                    if (get()) {
                        lblesito.setText("Ordinazione salvata con successo");
                        lblesito.setForeground(Color.GREEN);
                    } else {
                        lblesito.setText("Errore: Ordinazione non salvata");
                        lblesito.setForeground(Color.RED);
                    }
                } catch (Exception e) {
                    lblesito.setText("Errore: Ordinazione non salvata");
                    lblesito.setForeground(Color.RED);
                    e.printStackTrace();
                }
            }
        };

        worker.execute();
    }

    private void VaiAListaRistoranti() {
        navigator.showListaRistoranti();

        // Find the parent JFrame and dispose it
        /* Window window = SwingUtilities.getWindowAncestor(contentPane);
        if (window instanceof JFrame) {
            ((JFrame) window).dispose();
        }*/
    }

}
