package Boundary;

import Controller.OrdinazioneControllerStub;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class FormOrdinazione {
    private JPanel contentPane;
    private JButton indietroButton;
    private JButton confermaButton;
    private JTextField Piatto1;
    private JPanel Header;
    private JPanel Body;
    private JPanel Footer;
    private JSpinner spinner1;
    private JScrollBar scrollBar1;
    private JSpinner spinner2;
    private JSpinner spinner3;
    private JTextField Piatto2;
    private JTextField Piatto3;
    private JLabel NomeRistorante;
    private JLabel lblesito;


    /** Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.setPreferredSize(new Dimension(450, 300));
        Header = new JPanel();
        Header.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, 2));
        contentPane.add(Header, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        NomeRistorante = new JLabel();
        NomeRistorante.setText("NomeRistorante");
        Header.add(NomeRistorante, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(99, 27), null, 0, false));
        Body = new JPanel();
        Body.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(Body, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        Body.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, true));
        Piatto1 = new JTextField();
        Piatto1.setEditable(false);
        Piatto1.setText("Piatto 1");
        panel1.add(Piatto1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(262, 34), null, 0, false));
        spinner1 = new JSpinner();
        panel1.add(spinner1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_NORTHEAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        Body.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, true));
        Piatto2 = new JTextField();
        Piatto2.setEditable(false);
        Piatto2.setText("Piatto 2");
        panel2.add(Piatto2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(262, 34), null, 0, false));
        spinner2 = new JSpinner();
        panel2.add(spinner2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_NORTHEAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        Body.add(panel3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, true));
        Piatto3 = new JTextField();
        Piatto3.setEditable(false);
        Piatto3.setText("Piatto 3");
        panel3.add(Piatto3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(262, 34), null, 0, false));
        spinner3 = new JSpinner();
        panel3.add(spinner3, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_NORTHEAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblesito = new JLabel();
        lblesito.setText("EsitoInserimento");
        Body.add(lblesito, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Footer = new JPanel();
        Footer.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(Footer, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        indietroButton = new JButton();
        indietroButton.setText("Indietro");
        Footer.add(indietroButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        confermaButton = new JButton();
        confermaButton.setText("Conferma");
        Footer.add(confermaButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scrollBar1 = new JScrollBar();
        contentPane.add(scrollBar1, new GridConstraints(1, 1, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }


    // DA QUI IN POI è CODICE MIO
    //

    public FormOrdinazione() {
        $$$setupUI$$$();
        confermaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //stampaDati(); PROVA LISTENER
                SalvaOrdinazione();
            }
        });
        indietroButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                VaiAHome();
            }
        });
    }

    //PROVA LISTENER
    /*public void stampaDati() {
        String ristorante = NomeRistorante.getText();
        String piatto = Piatto1.getText();
        String spinner = spinner1.getValue().toString();

        System.out.println(ristorante);
        System.out.println(piatto);
        System.out.println(spinner);

    }*/
    private void SalvaOrdinazione() {
        String ristorante = NomeRistorante.getText();
        ArrayList<String> piatti = new ArrayList<String>();
        ArrayList<Integer> quantita = new ArrayList<Integer>();

        for (int i = 0; i < Body.getComponentCount(); i++) {
            Component c = Body.getComponent(i);
            if (c instanceof JPanel) {
                JPanel rigamenu = (JPanel) c;
                if (rigamenu.getComponentCount() > 0 && rigamenu.getComponent(0) instanceof JTextField) {
                    JTextField piatto = (JTextField) rigamenu.getComponent(0);
                    piatti.add(piatto.getText());
                    JSpinner quantita_ = (JSpinner) rigamenu.getComponent(1);

                    if ((int) quantita_.getValue() < 0) {
                        JOptionPane.showMessageDialog(null, "Inserire una quantità valida");
                    } else {
                        quantita.add((Integer) quantita_.getValue());
                    }
                }
            }
        }
        boolean esitoInserimento = OrdinazioneControllerStub.salvaOrdinazione(piatti, quantita);
        if (esitoInserimento) {
            lblesito.setText("Ordinazione salvata con successo");
            lblesito.setForeground(Color.GREEN);
        } else {
            lblesito.setText("Errore: Ordinazione non salvata");
            lblesito.setForeground(Color.RED);
        }
    }

    private void VaiAHome() {
        //qui va messo il codice per far ritornare l'uente alla schermata in cui deve scegliere tra i ristoranti
    }

    public static void main(String[] args) {
        JFrame frameOrdinazione = new JFrame();
        FormOrdinazione formOrdinazione = new FormOrdinazione();
        frameOrdinazione.setTitle("Ordinazione");
        frameOrdinazione.setContentPane(formOrdinazione.contentPane);
        frameOrdinazione.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frameOrdinazione.setResizable(false);
        frameOrdinazione.pack();
        frameOrdinazione.setLocationRelativeTo(null);
        frameOrdinazione.setVisible(true);
    }
}
